# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uoif3iIS6c5ob5BZSE4u00ABfjENV8Ck
"""



from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("messy_customer_data.csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

#Data Cleaning
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())

df['Gender'] = df['Gender'].str.strip().str.lower().map({
    'male': 'Male',
    'm': 'Male',
    'female': 'Female',
    'f': 'Female'
})

df['Churn'] = df['Churn'].str.strip().str.lower().map({
    'yes': 'Yes',
    'y': 'Yes',
    'no': 'No',
    'n': 'No'
})

df['TotalCharges'] = df['TotalCharges'].round(2)

df.drop_duplicates(inplace=True)

df['TotalCharges'] = df['TotalCharges'].round(2)
df['MonthlyCharges'] = df['MonthlyCharges'].round(2)

# Tenure in years
df['Tenure_Years'] = df['Tenure'] / 12

df['Tenure_Years'] = df['Tenure_Years'].round(2)

# Churn flag
df['Churn_Flag'] = df['Churn'].map({'Yes': 1, 'No': 0})

# Risk category
df['Risk'] = df.apply(lambda x: 'High Risk' if x['Tenure'] < 12 and x['MonthlyCharges'] > 70
                     else ('Medium Risk' if x['Tenure'] < 24 else 'Low Risk'), axis=1)

##Basic Analysis
#churn%
(df['Churn'].value_counts(normalize=True) * 100).round(2)

# Avg charges by churn
df.groupby('Churn')['MonthlyCharges'].mean().round(2)

# Tenure vs churn
df.groupby('Churn')['Tenure'].mean().round(2)

num_cols = df.select_dtypes(include=['float', 'int']).columns
df[num_cols] = df[num_cols].round(2)

df.to_csv("final_cleaned_data.csv", index=False)

from google.colab import files
files.download("final_cleaned_data.csv")